// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qikgizzowniozgetqlwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpa2dpenpvd25pb3pnZXRxbHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMTQ1MzksImV4cCI6MjA2NTg5MDUzOX0.bjRdmL6b69e1qDyhJ_kI9ldJ3F2EcwVWmQqRLcR867I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);